flutter_analyze_task:
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  pub_get_script: flutter pub get
  lint_script: flutter analyze

flutter_test_task:
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  test_script: flutter test

flutter_drive_ios_task:
  osx_instance:
    image: big-sur-xcode
  flutter_upgrade_script:
    - flutter upgrade
  open_simulator_script:
    - xcrun --version
    - xcrun simctl list
    - xcrun simctl create Flutter-iPhone com.apple.CoreSimulator.SimDeviceType.iPhone-12-Pro-Max com.apple.CoreSimulator.SimRuntime.iOS-14-4 | xargs xcrun simctl boot

  test_script: make test

flutter_drive_android_task:
  container:
    image: cirrusci/flutter:stable
    use_in_memory_disk: true
    kvm: true
    cpu: 4
    memory: 24G
  env:
    EMULATOR_API_LEVEL: 29
    ANDROID_ABI: "default;x86_64"
  fix_kvm_script: sudo chown $(whoami):$(whoami) /dev/kvm
  update_emulator_script: sdkmanager --verbose --channel=0 "emulator"
  update_images_script: sdkmanager "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
  create_device_script: echo no | avdmanager create avd --force -n test -k "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
  start_emulator_background_script: $ANDROID_HOME/emulator/emulator -verbose -avd test -no-audio -no-window
  wait_for_emulator_script:
    - ./scripts/android-wait-for-emulator.sh
  pub_cache:
    folder: ~/.pub-cache
  android_cache:
    folder: ~/.android/build-cache/
  test_script: make test
